### PR TITLE
add error message for class "difftime"

### LINKED ISSUE #215: Support additional data type
Using a column of class `difftime` as key or disp column in a listing is apparently not supported during export as txt and result in:
```
number of columns of matrices must match (see arg 2)
```

Could we consider less cryptic error message in `formatters::export_as_txt`, a warning in `as_listing` or just supporting this class ? Several users have come with the same issue.

Cheers

### PR DESCRIPTION
**Pull request by ayogasekaram**
closes #215 

Adding an error message for now for clarity - we can revisit supporting the "difftime" class type based on user requests.

### CODE REVIEW

**Comment by ayogasekaram** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Melkiades — COMMENTED** [review]
Great fix! we should do the same for {rtables}. It happens from time to time. Just wondering if it would be better to check this before creating the listing (and table). What do you think? I am quite sure that the one in {rtables} should be in build_table because it is the first checks when you see the data.

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @ayogasekaram 

we can merge this once https://github.com/insightsengineering/scda.test/pull/164 is green

**Review by BFalquet — COMMENTED** [review]
Same opinion as @Melkiades, I would put the test in `as_listings` so that it is clear the the error is due to the data, not subsequent modification of the listing. thank you.

**Comment by shajoezhu** [comment]
yes,  assertion in as_listings from the start, printing is too downstream

**Review by shajoezhu — CHANGES_REQUESTED** [review]
hi @ayogasekaram can you please update, use assertion

**Comment by ayogasekaram** [comment]
I've shifted the check to the as_listing function. I opted to not use the checkmate function because the error message seemed lengthy, but I can replace with this if required.
@shajoezhu 
image

**Review by shajoezhu — APPROVED** [review]
lgtm! thanks @ayogasekaram

**Pull request merged**
